### ISSUE TITLE
[BUG] - can't handle `allof` validator for valid schema

### ISSUE THREAD

**Issue by YonatanGreenfeld** [JaredCE/serverless-openapi-documenter#89] opened 2023-02-19 11:29 UTC
**Describe the bug**
Given the following valid json schema:
```json
{
  "title": "ParsingModel[RequestBody]",
  "$ref": "#/definitions/RequestBody",
  "definitions": {
    "Reason": {
      "title": "Reason",
      "description": "An enumeration.",
      "enum": [
        "1",
        "2"
      ],
      "type": "string"
    },
    "RequestBody": {
      "title": "RequestBody",
      "type": "object",
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "reason": {
          "default": "1",
          "allOf": [
            {
              "$ref": "#/definitions/Reason"
            }
          ]
        }
      },
      "required": [
        "id"
      ]
    }
  }
}
```
The plugin raises the following error:
```
  ServerlessError: AssertionError: expected Object {
    default: '1',
    allOf: Array [
      Object {
        title: 'Reason',
        description: 'An enumeration.',
        enum: Array [ '1', '2' ],
        type: 'string'
      }
    ]
  } to have property type
  ```
  
  If `allof` is omitted and the reference is placed in the outer scope like so:
  ```json
  {
  "title": "ParsingModel[RequestBody]",
  "$ref": "#/definitions/RequestBody",
  "definitions": {
    "Reason": {
      "title": "Reason",
      "description": "An enumeration.",
      "enum": [
        "1",
        "2"
      ],
      "type": "string"
    },
    "RequestBody": {
      "title": "RequestBody",
      "type": "object",
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "reason": {
          "default": "1",
              "$ref": "#/definitions/Reason"
        }
      },
      "required": [
        "id"
      ]
    }
  }
}
```
It will work as expected.

We can't control the schema output as it is automatically generated by [pydantic](https://docs.pydantic.dev/usage/schema/#getting-schema-of-a-specified-type)

**To Reproduce**
Use the given schema in the serverless.yml and run the plugin
**Expected behavior**
Using `allof` should act the same as omitting it as it is a valid schema

**Desktop (please complete the following information):**
 - Serverless version: 2.72.3
 - serverless-openapi-documenter version 0.0.46

**Comment by JaredCE** [comment] 2023-02-19 15:23
Hey @YonatanGreenfeld I believe your schema is correct, I think the issue is with the library I'm using to validate the outputted openAPI... liaising with that library owner currently so will see what comes out of that.  Will give it a little time, otherwise think i can add a rule to my schema massager to massage these instances into something the 3rd library accepts as valid.

**Comment by JaredCE** [comment] 2023-02-22 09:12
Right, 0.0.47 has just been published, that will fix this issue (i hope).  It's because `default` was outside of the allOf scope, so i've updated my json schema massager to pickup such properties and put them inside the scope.  it's valid JSON schema to have `default` defined outside of the scope, but OpenAPI JSON schema doesn't quite follow the same rules as standard JSON schema.  

Anyway, hopefully 0.0.47... let me know of any other issues.

Cheers

**Comment by JaredCE** [comment] 2023-02-26 11:14
Hey @YonatanGreenfeld I'm going to close this now as I believe it's fixed.  Please feel free to re-open this or raise any other issues you have with the plugin.  

Many thanks!

**Closed by JaredCE** 2023-02-26 11:14 UTC

**Comment by YonatanGreenfeld** [comment] 2023-02-26 11:26
Thank you @JaredCE ! I will check the new version and let you know if something's still not working
